version: '3.8'
services:
  dev-db:
    image: postgres:15 
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ulto
    networks:
      - local
networks:
  local:
